#!/usr/bin/env bash

if [ "$#" -ne 3 ]; then
    echo "usage: gunicorn_start.sh <user> <group> <num_workers>"
    exit
fi

export PYTHONPATH={{ home_dir }}/www/sse

[ -f /etc/default/sso_gunicorn ] && . /etc/default/sso_gunicorn

source {{ home_dir }}/env_setup.sh && exec gunicorn sse.wsgi:application \
--name core \
--user=$1 --group=$2 \
--workers $3 \
--timeout 60 \
--bind=unix:/opt/salt/sso/sse.sock \
--log-file=-
